### ISSUE TITLE
Unable to run ZWAD in ARM64 using Python 11

### ISSUE THREAD

**Issue by TorshaMajumder** [snad-space/zwad#138]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/__init__.py", line 45, in <module>
    from ._check_build import check_build  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/zwadp", line 5, in <module>
    from zwad.ad import ZtfAnomalyDetector
  
File "/Users/git/zwad/zwad/ad/__init__.py", line 9, in <module>
    from sklearn.mixture import GaussianMixture
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__init__.py", line 83, in <module>
    from . import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/__init__.py", line 47, in <module>
    raise_build_error(e)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError("""%s
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build/_check_build.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
___________________________________________________________________________
Contents of /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__check_build:
_check_build.cpython-311-darwin.so__init__.py               __pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

**Comment by hombit** [comment]
Hello @TorshaMajumder, it looks like you use mixed environment mixing ARM64/x86_64 python packages, while ARM64 are run natively and x86_64 are run via Rosetta2. I see that scikit-learn is installed to your global Python location, it does not look right, please try to setup virtual environment first:
```sh
python3.11 -mvenv ./path/to/new/virtual/environment/location/
source ./path/to/new/virtual/environment/location/bin/activate
```

Please note that you have to activate the environment each time you start a new shell session.

**Comment by TorshaMajumder** [comment]
@hombit, the error got fixed. Thanks!
