### ISSUE TITLE
Add possibility to continue from a stop point

### ISSUE THREAD

**Issue by pruzhinskaya** [snad-space/zwad#90]

**Comment by emilleishida** [comment]
This could be easily achieve  if we had the possibility to load previous answers. Starting with the same random seed we should probably be able to load answers from a file and just ask to the expert once that file is done. This would also avoid the need to save the pickle file -- at least for now.

**Comment by hombit** [comment]
@emilleishida for this we just need to dump one more file, with single `y` / `n` per each line, then we could just pipe content of this file to `zwaad` stdin

**Comment by hombit** [comment]
@matwey I think it is implemented now via `zwaad --prior_answers`?

**Comment by matwey** [comment]
I think so. Please, reopen if it doesn't work for you
